export const SUBSCRIPTIONS = 'subscriptions'
export const STREAMER_IMAGES = 'streamerImages'
export const SCHEDULE = 'schedule'
export const INCOMING_NOTIFICATIONS = 'incomingNotifications'
export const USER_CONFIGS = 'userConfigs'
